# Generated by Django 4.1.1 on 2022-09-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('brend', models.CharField(max_length=30)),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('olchov', models.CharField(choices=[('kg', 'kg'), ('tonna', 'tonna'), ('qop', 'qop')], max_length=12)),
                ('kelgan_sana', models.DateTimeField()),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.omborxona')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('qarz', models.IntegerField(default=0)),
                ('manzil', models.CharField(max_length=30)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.omborxona')),
            ],
        ),
    ]
