# Generated by Django 4.1.1 on 2022-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='olchov',
            field=models.CharField(choices=[('kg', 'kg'), ('dona', 'dona'), ('qop', 'qop')], max_length=12),
        ),
    ]
